name: givemore
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  firebase_core: ^0.4.0
  provider: ^4.0.5
  firebase_auth: ^0.14.0+5
  modal_progress_hud: ^0.1.3
  razorpay_flutter : ^1.1.1
  fluttertoast: ^3.1.0
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.0
  animations: ^1.1.1
  splashscreen: ^1.2.0
  font_awesome_flutter:
  line_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icon:
  android: 'launcher_icon'
  image_path: 'images/mylogo1.png'

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: Dancing Script
      
